# Generated by Django 2.2.6 on 2019-11-03 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='date_modified',
        ),
    ]
